config/routes.rb
Rails.application.routes.draw do

  root 'meetups#new'

  get "directions" => "meetups#directions"

  get 'sessions/new'
  post 'sessions/new' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  resources :pages

  resources :users
  resources :meetups


  resources :users do
  resources :meetups
end

resources :meetups

get "meetup/:slug" => "meetups#show"
get "directions" => "meetups#directions"
get "random_event" => "meetups#random"
get "cancel_event" => "meetups#cancel"
get "leave_event" => "meetups#leave"
get "about" => "pages#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_many :meetup_users
  has_many :users, through: :meetup_users
  belongs_to :guest_user
def generate_slug
  self.slug = SecureRandom.hex(12)
  self.save
end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'
  require 'httparty'
  require 'yelp/fusion'
  before_action :current_meetup, only: [:cancel, :leave]
  before_action :current_meetup_slug, only: [:show, :directions]

  def new
      @user = User.new
    if current_user == nil
      @eat_area = params[:eat_area]
      session[:location] = @eat_area
      unless @eat_area != nil
    else
      @meetup = Meetup.new
      @client = Yelp::Fusion::Client.new(ENV['YELP_API'])
      @results = @client.search("#{@eat_area}", term: 'restaurants')
      @yelp_response = JSON.parse(@results.to_json)
    end
    elsif
      @eat_area = params[:eat_area]
      session[:location] = @eat_area
      if @eat_area == nil
      else
        @user = current_user
        @meetup = Meetup.new
        @client = Yelp::Fusion::Client.new(ENV['YELP_API'])
        @results = @client.search("#{@eat_area}", term: 'restaurants')
        @yelp_response = JSON.parse(@results.to_json)
        end
      end
     end


  def create
    if current_user == nil
      @meet_date = params[:meet_date]
      @meet_time = params[:meet_time]
      @location = params[:location]
      @location_name = params[:location_name]
      @meetup = Meetup.new(
        meet_date: @meet_date,
        meet_time: @meet_time,
        location: @location,
        location_name: @location_name,
        guest_user: GuestUser.new)
      p "creating guest user..."
      session[:destination_address] = @location
      if @meetup.save
      guest = GuestUser.create(name: params["meetup"]["name"],
                            phone: params["meetup"]["phone"],
                            email: params["meetup"]["email"]) #create and validate is the correct way
      p "guest user created"
      GuestUserMailer.confirmation_email(guest).deliver_now
      @meetup.guest_user_id = guest.id
      @meetup.generate_slug
      redirect_to("/meetup/#{@meetup.slug}")
      end
    else
    @meetup = Meetup.new(meetup_params)
    @meetup.user_one = current_user.id
    @meetup.guest_user = GuestUser.new # This is a workaround for the rollback transaction
    p "Meetup Creation Debugging"
    p @meetup.errors.messages # Ted added this
    @meetup.save
    p "Error Debugging"
    p @meetup.errors.messages # Ted added this
    redirect_to current_user
    end
  end

  def edit
  end

  def index
  end

  def show
    @meetup = Meetup.find_by(slug: params[:slug])
  end

  def random
    if current_user == nil
      all = Meetup.all
      p "STUFF"
      only_guest_meetup = all.where(joiner_id: nil).shuffle[0]
      guest = GuestUser.create(name: params["meetup"]["name"],
                            phone: params["meetup"]["phone"],
                            email: params["meetup"]["email"])
    only_guest_meetup.joiner_id = guest.id
    only_guest_meetup.save

    joining_user = GuestUser.find(only_guest_meetup.joiner_id)
    creator_user = GuestUser.find(only_guest_meetup.guest_user_id)

    creator_emailinfo = {:email => creator_user.email,:location => only_guest_meetup.location,:meet_time => only_guest_meetup.meet_time,:meet_date => only_guest_meetup.meet_date,:location_name => only_guest_meetup.location_name}
    joiner_emailinfo = {:email => joining_user.email,:location => only_guest_meetup.location,:meet_time => only_guest_meetup.meet_time,:meet_date => only_guest_meetup.meet_date,:location_name => only_guest_meetup.location_name}

    GuestUserMailer.join_email(creator_emailinfo).deliver_now
    GuestUserMailer.join_email(joiner_emailinfo).deliver_now

    redirect_to("/meetup/#{only_guest_meetup.slug}")
  else
     # random = User.all.ids.shuffle[0]
     # current_meetup = Meetup.find_by(random.to_s)
     random = Meetup.all.length - 1
     meetups = Meetup.all.select{|meetup| meetup.user_one != nil}
     current_meetup = meetups.find(random).each do |key,value|
       [key,value]
     end
     if (current_meetup.user_two == nil && current_meetup.user_one != current_user.id)
       current_meetup.user_two = current_user.id
       current_meetup.save
       redirect_to current_user
     end # if (current_meetup.user_two == nil && current_meetup.user_one != current_user.id)
   end
   end

  def cancel
    @current_meetup.destroy
    redirect_to current_user
  end

  def leave
    @current_meetup_joined.user_two = nil
    @current_meetup_joined.save
      redirect_to current_user
    end

    def directions
    if current_user == nil
    redirect_to "https://www.google.com/maps/dir/?api=1&origin=#{session[:location]}&destination=#{session[:destination_address]}&travelmode=walking"
    elsif Meetup.find_by(user_one: current_user.id) != nil
      redirect_to "https://www.google.com/maps/dir/?api=1&origin=#{session[:location]}&destination=#{@current_meetup.location}&travelmode=walking"
    elsif Meetup.find_by(user_two: current_user.id) != nil
      redirect_to "https://www.google.com/maps/dir/?api=1&origin=#{session[:location]}&destination=#{@current_meetup_joined.location}&travelmode=walking"
    else
      p @current_meetup
      p @current_meetup_joined
      redirect_to current_user
    end
    end

  private

  def meetup_params
    params.require(:meetup).permit(:user_one, :meet_date, :meet_time, :location, :guest_user, :location_name)
  end

  def current_meetup
    @current_meetup = Meetup.find_by(user_one: current_user.id)
    @current_meetup_joined = Meetup.find_by(user_two: current_user.id)
  end

  def current_meetup_slug
      @meetup = Meetup.find_by(slug: params[:slug])
    end

end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/edit.html.erb
<h1>Meetups#edit</h1>
<p>Find me in app/views/meetups/edit.html.erb</p>

app/views/meetups/index.html.erb
<div class="">
  <h1>Meetups#index</h1>
  <p>Find me in app/views/meetups/index.html.erb</p>
</div>

app/views/meetups/new.html.erb
<div class="main">
  <div class="popup">
    <div class="signup">
      <%= render 'users/form' %>
    </div>
    <div class="login">
      <%= render 'sessions/form' %>
    </div>
  </div>
  <div class="headline">
    <div class="location">

      <% if current_user == nil %>
        <div class="pickLocation">
          <%= form_tag(new_meetup_path, method: "get") do %>
          <h3 class="question">where would you like to eat?</h3>
          <%= label_tag(:eat_area, "Enter Address: ") %><%= text_field_tag(:eat_area) %>
          <br>
          <%= button_tag "Get Places!", class: 'form_button' %>
        <% end %>
      </div>
      <div class="join">
        <% if Meetup.find_by(joiner_id: nil) != nil %>
          <h3 class="question">Would you like to join a random lunch?</h3>
          <%= form_tag(random_event_path, method: "get") do %>
          <label for="meetup[name]">Your Name:
          </label>
          <input type="text" name="meetup[name]">
          <br>
          <label for="meetup[phone]">Your Phone Number:
          </label>
          <input type="text" name="meetup[phone]">
          <br>
          <label for="meetup[email]">Email Address:
          </label>
          <input type="text" name="meetup[email]">
          <br>
          <%= button_tag "Join!", class: 'form_button' %>
        <% end %>
      </div>
    <%else%>
      <h3 class="question">
        No meetups you can join yet! Why don't you create one?
      </h3>
    <%end%>
  </div>

  <!---location end--->
  <% if @eat_area != nil %>
    <div class="yelpList">
      <% @yelp_response["businesses"].each do |b| %>
        <div class="grid-item yelp">
          <h4>
            <%= b['name']%></h4>
          <p> <span class="label">Address:</span>
            <%= b['location']['address1']%>,
            <%= b['location']['city']%>,
            <%= b['location']['zip_code']%></p>
          <p> <span>Price:</span>
            <%= b["price"] %></p>
          <p><span>Rating:</span>
            <% if b["rating"] != nil %>
            <% b["rating"].to_i.times do %>
          <img class="star" src="https://png.pngtree.com/svg/20170626/star_rating_425874.png" size="20px">
          <% end %>
          <% end %>
          <p><span>Reviews:</span>
            <%= @client.review(b["id"]).reviews[0].text %></p>
            <hr>
          <%= form_for [@meetup] do |m| %>
          <% @location = b['location']['address1'] + " " + b['location']['city'] + " " + b['location']['zip_code'] %>
            <label for="meet_time">Meet Time:
            </label>
            <input type="time" name="meet_time" required="required">
            <br>
            <label for="meet_date">Meet Date:
            </label>
            <input type="date" name="meet_date" required="required">
            <br>
            <label for="meetup[name]">Your Name:
            </label>
            <input type="text" name="meetup[name]" required="required">
            <br>
            <label for="meetup[phone]">Your Phone Number:
            </label>
            <input type="text" name="meetup[phone]" required="required">
            <br>
            <label for="meetup[email]">Email Address:
            </label>
            <input type="text" name="meetup[email]" required="required">
            <br>
            <input type="text" name="location" value="<%= @location %>" hidden="hidden" required="required">
            <br>
            <input type="text" name="location_name" value="<%= b['name'] %>" hidden="hidden" required="required">
            <br>
            <input type="submit" name="" value="Create meetup" class="form_button">
          <%end%>
        </div>
      <%end%>
    </div>
<%else%>
  <div class="landbox">
    <img src="/logo_transparent.png" alt="" class="logo">
    <p>Plate-onicly is a place for strangers to meet and have lunch. We were founded in 2018, to help strangers not eat alone. We wanted to create an experience where two people can come together and share bread ... or pasta ... or a burger together. You can have a real conversation. Create an event or join a random event. For guest users it is truly random, so if you would like more options, go ahead and create an account with us. Won't you join us to have lunch with a stranger! At Plate-onicly there's a plate for everyone. </p>

    </div>
<%end%>
</div>
<% else %>

<div class="headline">
  <div class="location">
    <div class="pickLocation">
      <h2>Where area you like to eat?</h2>
      <%= form_tag(new_meetup_path, method: "get") do %>
      <%= label_tag(:eat_area, "Enter Address") %><%= text_field_tag(:eat_area) %>
      <br>
      <%= submit_tag "Get Places!" %>
    <% end %>
  </div>
  <div class="join">
    <h2>Click here to meetup</h2>
    <!-- <button type="button" name="button">Join</button> -->
    <%= link_to "Join Random Event", random_event_path %>
  </div>

</div>

<!-- Location End  -->

<% if @eat_area != nil %>
  <div class="yelpList">
    <% @yelp_response["businesses"].each do |b| %>
      <div class="grid-item yelp">
        <p>Name:
          <%= b['name']%></p>
        <p>Address:
          <%= b['location']['address1']%>,
          <%= b['location']['city']%>,
          <%= b['location']['zip_code']%></p>
        <p>Price:
          <%= b["price"] %></p>
        <p>Rating:
          <% if b["rating"] != nil %>
          <% b["rating"].to_i.times do %>
          <img class="star" src="https://png.pngtree.com/svg/20170626/star_rating_425874.png" size="20px">
          <% end %>
          <% end %>
        <p>Reviews:
          <%= @client.review(b["id"]).reviews[0].text %></p>
        <%= form_for @meetup do |m| %>
        <%= m.time_select :meet_time, start_hour: 8, end_hour: 20, minute_step: 30, include_day: false, include_year: false, include_month: false, required: true %>
        <br>
        <%= m.date_select :meet_date, :order => [:month, :day, :year], start_year: (Time.now.year), required: true %><br>
        <%= m.text_field :location, value: "#{b['location']['address1']}, #{b['location']['city']}, #{b['location']['zip_code']}", hidden: true, required: true %>
        <%= m.text_field :location_name, value: "#{b['name']}", hidden: true, required: true %>
        <%= m.submit %>
      <%end%>
    </div>
  <% end %>
</div>
<% else %>
<div class="landbox">
  <img src="/logo_transparent.png" alt="" class="logo">
  <p>Plate-onicly is a place for strangers to meet and have lunch. We were founded in 2018, to help strangers not eat alone. We wanted to create an experience where two people can come together and share bread ... or pasta ... or a burger together. You can have a real conversation. Create an event or join a random event. For guest users it is truly random, so if you would like more options, go ahead and create an account with us. Won't you join us to have lunch with a stranger! At Plate-onicly there's a plate for everyone. </p>

  </div>

<% end %>

</div>
<% end %>
</div>

app/views/meetups/show.html.erb
<div class="meetup">
  <h3> Your meet up at <%= @meetup.location_name %>. </h3>
  <h2>For directions.</h2>
 <%= link_to "Directions!", directions_path , target: '_blank', class: 'form_button'%>
</div>