config/routes.rb
Rails.application.routes.draw do

  root 'meetups#new'

  get "directions" => "meetups#directions"

  get 'sessions/new'
  post 'sessions/new' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  resources :pages

  resources :users
  resources :meetups


  resources :users do
  resources :meetups
end

resources :meetups

get "meetup/:slug" => "meetups#show"
get "directions" => "meetups#directions"
get "random_event" => "meetups#random"
get "cancel_event" => "meetups#cancel"
get "leave_event" => "meetups#leave"
get "about" => "pages#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_secure_password
  has_many :meetup_users
  has_many :meetups, through: :meetup_users
  has_and_belongs_to_many :interests
  # has_and_belongs_to_many :interests
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  # VALID_PHONE_REGEX = /\d/m
  # validates :phone_number, presence: true, length: {minimum: 10, maximum: 10}, format: { with: VALID_PHONE_REGEX }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :current_meetup, only: [:show, :directions, :cancel, :update]

  def new
    @user = User.new
    categories = ['Technology','TV','Business','Politics','Travel','Games','Movies','Theatre','Sports','Fashion']
    categories.each do |category|
      interest = Interest.new(name: category)
      match = Interest.find_by(name: interest.name)
      if !match
        interest.save
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
    else
      p @user.errors.messages
      render 'new'
    end
  end

  def edit
      @user = User.find(params[:id])
      
  end



  def show
    @user = User.find(params[:id])
  end

  def index
      redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:first_name,:last_name,:age,:phone_number,:email,:password,:password_confirmation,interest_ids:[])

  end


  def current_meetup
    @current_meetup = Meetup.find_by(user_one: current_user.id)
    @current_meetup_joined = Meetup.find_by(user_two: current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h1 class="question">Add a new user</h1>
<%= form_for(@user) do |f| %>
<label>Email:</label><br>
<%= f.email_field :email, placeholder: "Email", required: true %><br><br>
<label>First Name:</label><br>
<%= f.text_field :first_name, placeholder: "First Name", required: true %><br><br>
<label>Last Name:</label><br>
<%= f.text_field :last_name, placeholder: "Last Name", required: true %><br><br>
<label>Age:</label><br>
<%= f.number_field :age, placeholder: "Age", min:18, max:120, required: true %><br><br>
<label>Phone:</label><br>
<%= f.text_field :phone_number, placeholder: "Phone Number", pattern: "[0-9]{10}", required: true %><br><br>

<!-- Checkbox field begins -->
<div class="field">
  <%= f.label "Interests" %><br>
  <%= f.collection_check_boxes :interest_ids, Interest.all, :id, :name do |b| %>
  <div class="collection-check-box">
    <%= b.check_box %>
    <%= b.label %>
  </div>
<% end %>
</div><br>
<!-- Checkbox field ends -->

<label>Password:</label><br>
<%= f.password_field :password, placeholder: "Password", required: true %><br><br>
<label>Confirm Password:</label><br>
<%= f.password_field :password_confirmation, placeholder: 'Confirm Password', required: true %><br><br>

<input type="submit" name="" value="Sign up" class="form_button"><input type="" name="" value="close" class="form_button close">
<% end %>

app/views/users/edit.html.erb
<h2>Editing <%= @user.first_name %> <%= @user.last_name %></h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="userHome">

  <% if logged_in? %>
    <h2 class="question">Welcome
      <%= @user.first_name %>
      <%= @user.last_name %>
    </h2>
    <h3>Your Interests:</h3>
    <% @user.interests.each do |interest| %>
      <%= interest.name %><br>
    <% end %><br>

    <button class="userBtn"><%= link_to "Edit Information", edit_user_path %></button> <br>

    <% if @current_meetup == nil and @current_meetup_joined == nil %>
      <button class="userBtn"><%= link_to "Create Event", new_user_meetup_path(current_user) %></button>
      <br>
    <% end %>
    <% if @current_meetup == nil and @current_meetup_joined == nil %>
      <button class="userBtn"><%= link_to "Join Random Event", random_event_path %></button><br>
    <% end %>

    <% if @current_meetup != nil %>
      <button class="userBtn"><%= link_to "Current Event", user_meetup_path(current_user) %></button><br>
      <button class="userBtn"><%= link_to "Cancel/End Event", cancel_event_path %></button><br>
      <% elsif @current_meetup_joined != nil %>
        <button class="userBtn"><%= link_to "Current Event", user_meetup_path(current_user) %></button><br>
        <button class="userBtn"><%= link_to "Leave Event", leave_event_path %></button><br>
      <% else %>
      <% end %>

    <% else %>
      <h1>(You are not logged in)</h1>
    <% end %>
  </div>