config/routes.rb
Rails.application.routes.draw do

  root 'meetups#new'

  get "directions" => "meetups#directions"

  get 'sessions/new'
  post 'sessions/new' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  resources :pages

  resources :users
  resources :meetups


  resources :users do
  resources :meetups
end

resources :meetups

get "meetup/:slug" => "meetups#show"
get "directions" => "meetups#directions"
get "random_event" => "meetups#random"
get "cancel_event" => "meetups#cancel"
get "leave_event" => "meetups#leave"
get "about" => "pages#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav>
  <button type="button" name="button" class="menu">Menu</button>
  <ul class="hidenav">
    <li>
      <a href="/">Home</a>
    </li>
    <% if logged_in? %>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to("Log out",sessions_logout_path,method: :delete, data: {confirm: 'Are you sure?'}) %></li>
    <% else %>
      <li class="signupNav">
        <!-- <div class="soon">
          <p>Coming Soon!</p>
        </div> -->
      <a href="#">Sign up</a>
    </li>
    <li class="loginNav">
      <!-- <div class="soon">
        <p>Coming Soon!</p>
      </div> -->
    <a href="#">Log in</a>
  </li>
<% end %>
<li>
  <a href="/about">About</a>
</li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Plate-onicly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kanit" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav'%>

    </header>
    <%= yield %>
    <div class="footer">
     <h3 class="footerLogo">2018 Plate-onicly</h3>
       <img src="/logo_transparent.png" alt="" class="image-footer">
     <div class="social">
     <i class="fab fa-facebook"></i>
     <i class="fab fa-instagram"></i>
     <i class="fab fa-twitter-square"></i>
     <i class="fab fa-yelp"></i>
   </div>
</div>
  </body>
</html>